<?php
echo \Mvc\Registry::getInstance()->get('viewDoctype');
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>My Test</title>

<!-- CSS Files -->
<?php
    if (!is_null(\Mvc\Registry::getInstance()->get('viewHeader'))) {
        echo \Mvc\Registry::getInstance()->get('viewHeader') . PHP_EOL;
    }
?>
</head>
<body>
    <div id="navi">
    </div>
<?php
echo \Mvc\Registry::getInstance()->get('viewContent');
?>
<?php
if (!is_null(\Mvc\Registry::getInstance()->get('viewFooter'))) {
    echo \Mvc\Registry::getInstance()->get('viewFooter') . PHP_EOL;
}
?>
</body>
</html>