<?php
echo \Mvc\System::getInstance()->viewDoctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>My Test</title>

<!-- CSS Files -->
<?php
    if (!is_null(\Mvc\System::getInstance()->viewHeader())) {
        echo \Mvc\System::getInstance()->viewHeader() . PHP_EOL;
    }
?>
</head>
<body>
    <div id="navi">
    </div>
<?php
echo \Mvc\System::getInstance()->viewContent();
?>
<?php
if (!is_null(\Mvc\System::getInstance()->viewFooter())) {
    echo \Mvc\System::getInstance()->viewFooter() . PHP_EOL;
}
?>
</body>
</html>